import type { AppProps } from 'next/app'
import Head from 'next/head'
import { useEffect } from 'react'

import '~/global.css'
import { app } from '~/store'

export default function App({ Component, pageProps }: AppProps) {
  useEffect(() => {
    app.init()
  }, [])

  return (
    <>
      <Head>
        <title>React MobX Starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Component {...pageProps} />
    </>
  )
}
